spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5433/testdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update